### ISSUE TITLE
Strange elpased time

### ISSUE THREAD

**Issue by darron1217** [romanzipp/Laravel-Queue-Monitor#1]
I installed this package and it seems working well.
But I found elapsed time is calculated stragely

![image](https://user-images.githubusercontent.com/8064923/39982720-32c9ecb8-5790-11e8-97a7-c2d539bbc75c.png)

started_at: `2018-05-14 15:54:12`
finished_at: `2018-05-14 15:59:04`

Correct calcuation was...
59:04 - 54:12 = 4:52 = 292 sec
but on database, elapsed time is stored as 52 sec

**Comment by darron1217** [comment]
Thanks :)

**Comment by romanzipp** [comment]
Looks like the elapsed time calculation is still a bit buggy

![2018-05-16 14_16_38-vm-1_pietsmiet_laravel_queue_monitor_ - heidisql 9 5 0 5196](https://user-images.githubusercontent.com/11266773/40116400-db791e54-5913-11e8-840e-9d0676560839.png)

**Comment by darron1217** [comment]
Yes, I found that bug too

**Comment by darron1217** [comment]
I created PR to fix the bug :)

**Comment by romanzipp** [comment]
Thanks! Included in [1.2.0](https://github.com/romanzipp/Laravel-Queue-Monitor/releases/tag/1.2.0)
