### ISSUE TITLE
Feature: Show pending jobs

### ISSUE THREAD

**Issue by itpilotdk** [romanzipp/Laravel-Queue-Monitor#100]
It would be really nice to se all the (not started) "pending" jobs together with this dashboard.

**Comment by fh32000** [comment]
@itpilotdk @eboye @owenconti @darron1217 @huzaifaarain

**Comment by romanzipp** [comment]
I think this functionality is out of the packages scope. If you're using the database job queue you could just add a custom model using the `jobs` table
