### ISSUE TITLE
Auto clean-up task?

### ISSUE THREAD

**Issue by javis** [romanzipp/Laravel-Queue-Monitor#105]
It would be useful to have a laravel command to clean up old tasks on a schedule. Is there anything like that planned for the package?

**Comment by romanzipp** [comment]
I'm planning on adding such a command in version 3 of this package. Already working on #103 but I don't have much time working on this right now. Should be finished in Q1 2023

**Comment by javis** [comment]
That sounds great, thanks!

**Comment by romanzipp** [comment]
I've finished work on the next major version **3.0** (PR #103)  which will resolve this issue but also contains some **breaking changes**. Would you be willing to test this version out before I tag a stable release?

Please reference the [**upgrade guide**](https://github.com/romanzipp/Laravel-Queue-Monitor/releases/tag/untagged-2df26f2371011896f24c) for further instructions.

```sh
composer require romanzipp/laravel-queue-monitor "^3.0.0"
```

**Comment by javis** [comment]
Hi! thanks for looking into this, I will test this version now.

**Comment by javis** [comment]
I don't know if this is an actual issue, but this is what I get when I run that composer require command you sent me:

![image](https://user-images.githubusercontent.com/951888/224787302-6fc28d0d-3fe8-46d7-8758-cac98999e9ed.png)

**Comment by javis** [comment]
Hi! the route configuration doesn't seem to be working for me, I can not access the UI page

**Comment by romanzipp** [comment]
Thanks for testing! Did you change your current `queue-monitor.php` config file for the newly added values [`ui.enabled`](https://github.com/romanzipp/Laravel-Queue-Monitor/blob/v3/config/queue-monitor.php#L23) and [`ui.route`](https://github.com/romanzipp/Laravel-Queue-Monitor/blob/v3/config/queue-monitor.php#L23)?

**Comment by javis** [comment]
Yes I did! :)
