### ISSUE TITLE
Attribute [queueMonitor] does not exist.

### ISSUE THREAD

**Issue by mhapach** [romanzipp/Laravel-Queue-Monitor#106]
After adding to my web.php
```
Route::prefix('jobs')->group(function () {
    Route::queueMonitor();
});
```
I have got  such error 

```
Attribute [queueMonitor] does not exist.
```
Laravel 9.44

**Comment by romanzipp** [comment]
Did you try running `composer dump-autoload`?

**Comment by mhapach** [comment]
yes

**Comment by mhapach** [comment]
may be you forgot  smth to explain in read.me  in config/app.php - for example to include service provider in 'providers'

**Comment by romanzipp** [comment]
This *should* happen automatically, if this doesn't work either you could add the routes manually by now.
Just move the route declaration to your web.php routes file an replace the method calls with `Router::` https://github.com/romanzipp/Laravel-Queue-Monitor/blob/master/src/Routes/QueueMonitorRoutes.php

**Comment by mhapach** [comment]
I've made so 

```
Route::prefix('/jobs')->group(function() {
    /** @var \Illuminate\Routing\Router $this */
    Route::get('', '\romanzipp\QueueMonitor\Controllers\ShowQueueMonitorController')->name('queue-monitor::index');
}

```
and got such error in middleware 
```
Class name must be a valid object or a string 
at return $next($request); 
```

if I put code in web.php without middleware
I've gor such error in index.php at  $request = Request::capture()
```
Class name must be a valid object or a string
```

**Comment by romanzipp** [comment]
I've finished work on the next major version **3.0** (PR #103)  which will resolve this issue but also contains some **breaking changes**. Would you be willing to test this version out before I tag a stable release?

Please reference the [**upgrade guide**](https://github.com/romanzipp/Laravel-Queue-Monitor/releases/tag/untagged-2df26f2371011896f24c) for further instructions.

```sh
composer require romanzipp/laravel-queue-monitor "^3.0.0"
```

**Comment by mhapach** [comment]
Same error
It seems to me that problem in vendor path 
your current path is romanzipp/laravel-queue-monitor
but in 
vendor/romanzipp/laravel-queue-monitor/composer.json you use
    "autoload": {
        "psr-4": {
            "romanzipp\\QueueMonitor\\": "src"
        }
    },
or 
    "extra": {
        "laravel": {
            "providers": [
                "romanzipp\\QueueMonitor\\Providers\\QueueMonitorProvider"
            ]
        }
    },
there is no such path.
