### ISSUE TITLE
Trait doesn't work if you extend it or use it in a parent class

### ISSUE THREAD

**Issue by maxim-grin** [romanzipp/Laravel-Queue-Monitor#12]
Steps to reproduce for scenario 1:

TestTrait.php
//////
namespace App\Traits;
use romanzipp\QueueMonitor\Traits\QueueMonitor;

trait TestTrait
{
    use QueueMonitor;
}
//////

TestClassOne.php
//////
namespace App;
use App\Traits\TestTrait;
class TestClass {
use TestTrait;
// no monitoring will work in this class
}
//////

Steps to reproduce for scenario 2:

ParentClass.php
//////
namespace App;
use romanzipp\QueueMonitor\Traits\QueueMonitor;

class ParentClass
{
    use QueueMonitor;
}
//////

ChildClass.php
//////
namespace App;
use App\ParentClass;
class ChildClass extends ParentClass{
// no monitoring will work in this class
}
//////

Possible solution:
in romanzipp\QueueMonitor\QueueMonitorHandler->shouldBeMonitored(Job $job)
replace [class_uses()](https://www.php.net/manual/en/function.class-uses.php) with  [class_uses_recursive()](https://laravel.com/docs/5.5/helpers#method-class-uses-recursive)

**Comment by maxim-grin** [comment]
---return array_key_exists(QueueMonitor::class, class_uses($class));
+++return array_key_exists(QueueMonitor::class, class_uses_recursive($class));

**Comment by romanzipp** [comment]
Resolved in [2.0.0](https://github.com/romanzipp/Laravel-Queue-Monitor/releases/tag/2.0.0)
