### ISSUE TITLE
Error with postgres

### ISSUE THREAD

**Issue by Chris1234567899** [romanzipp/Laravel-Queue-Monitor#121]
Hi, I'm receiving an error when trying to acess the ui page:

![image](https://user-images.githubusercontent.com/12623865/232107989-c55330e6-67ea-4c38-9047-918e5154a9fa.png)

This is the query exception I caught in detail:
```
  #message: """
    SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ","
    LINE 1: ...) as count, SUM(TIMESTAMPDIFF(SECOND, `started_at`, `finishe...
                                                                 ^ (Connection: pgsql, SQL: select COUNT(*) as count, SUM(TIMESTAMPDIFF(SECOND, `started_at`, `finished_at`)) as `total_time_elapsed`, AVG(TIMESTAMPDIFF(SECOND, `started_at`, `finished_at`)) as `average_time_elapsed` from "queue_monitor" where "status" != 0 and "started_at" >= 2023-03-31 16:45:14 limit 1)
```

I think the problem is "TIMESTAMPDIFF". As far as I know, this is not a thing in postgres...
Probably it needs a dedicated workaround like https://github.com/romanzipp/Laravel-Queue-Monitor/issues/117

**Comment by romanzipp** [comment]
Could you check if #122 resolves this issue=

**Comment by Chris1234567899** [comment]
Not working yet, but we're almost there ;-)
See the comment I added.
