### ISSUE TITLE
middleware issue

### ISSUE THREAD

**Issue by bdj-Razik** [romanzipp/Laravel-Queue-Monitor#130]
when i put auth middleware in file config : 
  
// Accepts route group configuration 
'route' => [
                    'prefix' => 'jobs',
                     'middleware' =>  'auth', error [] operator not supported for strings
                     'middleware' =>  ['auth'] ,  middleware not working
],

**Comment by romanzipp** [comment]
Please try adding your `web` middleware group - not just the `auth` middleware. https://github.com/romanzipp/Laravel-Queue-Monitor/issues/120

**Comment by bdj-Razik** [comment]
soory sur  if i want to protect this page when user authentificate  with web middleware is not working

**Comment by romanzipp** [comment]
I'm afraid I don't understand what you're trying to tell me. Did you try adding `['web', 'auth']`? What is the exact issue you're facing? Any error messages?

**Comment by bdj-Razik** [comment]
thank's its work
