### ISSUE TITLE
Doesn't add new queues

### ISSUE THREAD

**Issue by nikolajgromkov** [romanzipp/Laravel-Queue-Monitor#132]
My config file contain all queues
`'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
            'queue' => ['default', 'events', 'nomenclature', 'nomenclature_chunk', 'orders', 'contracts', 'tradesmen', 'stocks', 'contragents', 'orders_export'],
            'retry_after' => 9000,
            'block_for' => null,
            'after_commit' => false,
        ],
`
But they didn't show up in the monitor https://i.imgur.com/07X9jiW.png
All other queues work fine. It looks like he fixed the queues during installation and no longer looks at others

**Missing: order_export, nomenclature_chunk, events**

Laravel 8, Queue Monitor latest version 4.0

**Comment by romanzipp** [comment]
The displayed queues are only taken from existing monitored jobs.

https://github.com/romanzipp/Laravel-Queue-Monitor/blob/master/src/Controllers/ShowQueueMonitorController.php#L61
