### ISSUE TITLE
SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "," LINE 1: ...) as count, SUM(TIMESTAMPDIFF(SECOND, `started_at`, `finishe...

### ISSUE THREAD

**Issue by mobreviews** [romanzipp/Laravel-Queue-Monitor#135]
I've just installed this package and I'm trying to use the web interface but I get this error message.  Any ideas?  I'm running Laravel 10 on php 8.1 with a Postgres 15 database.

**Comment by romanzipp** [comment]
Please post the full stacktrace in the issue description, not the title

**Comment by mobreviews** [comment]
https://flareapp.io/share/x7XrEApm

**Comment by romanzipp** [comment]
Please be more detailed in your bug reports. 
Which version of the queue monitor package are you using?
It looks like you're using PostgreSQL, have you configured the database connection with the correct driver?

**Comment by mobreviews** [comment]
As I said I just installed it so it is the latest version - 4.0.2

**Comment by romanzipp** [comment]
I added improved support for PostgreSQL & SQLite in 5.0. Could you try if version [5.0.0-rc.2](https://github.com/romanzipp/Laravel-Queue-Monitor/releases/tag/5.0.0-rc.2) works for you?

**Comment by mobreviews** [comment]
can this be upgraded via composer or do I need to do it manually?

**Comment by mobreviews** [comment]
ok did it manually and that appears to have solved the issue thanks
