### ISSUE TITLE
Undefined variable: ffmpeg

### ISSUE THREAD

**Issue by lakshsyal123** [romanzipp/Laravel-Queue-Monitor#15]
Hello I just used it as mention in the documentation

But this is what I see when I use it.

https://prnt.sc/q1zugd

any comment on how can I fix this?

**Comment by romanzipp** [comment]
The `$ffmpeg` varaible was just an example on how to use the progress feature. This is not part of the package itself.

**Comment by lakshsyal123** [comment]
How can I use that feature to track the progress on my job?

Can you create a better example of it?

**Comment by romanzipp** [comment]
I don't know what type of job you're trying to accomplish. The `$this->qeueueProgress()`method can be implemented in any way you like. It just writes the given value into the database.
