### ISSUE TITLE
Any plans for GUI?

### ISSUE THREAD

**Issue by damms005** [romanzipp/Laravel-Queue-Monitor#16]
Would be nice to have a nice TailwindCss-powered UI for the `Monitor` model. Any plans?

P.S.: I am not good with designing UI/prototyping but if @romanzipp /contributors are not readily available to work on this and @romanzipp does not mind including it,then I am available to work with anyone that can help protype (e.g. using Figma?) a nice and clean UI for this awesome package

**Comment by romanzipp** [comment]
I've already thought about a GUI but I don't know which would be best. Standalone like Laravel Horizon, Vue component, Blade component.. What are your thoughts on this?

**Comment by damms005** [comment]
Depends on how much minimalism we are willing to trade-off for efficiency.

At the peak of efficiency (something that devs will like and want to use, [better DX](https://medium.com/@albertcavalcante/what-is-dx-developer-experience-401a0e44a9d9), I will say we should go with a full blown Vue-powered front-end with live updates (using simple [server-side sockets implementation like this](https://github.com/beyondcode/laravel-websockets)).

At the other farther end of the spectrum - minimalism, we can simply go with a simple paginated blade template (like attached below screenshot of something I hurriedly did for my [Voyager](https://github.com/the-control-group/voyager)-powered admin backend):

![image](https://user-images.githubusercontent.com/9839355/70847723-e4f5cc00-1e67-11ea-9584-225328e82426.png)

**Comment by romanzipp** [comment]
I've started working on a GUI, see #21 Would love to get some feedback in this

**Comment by underdpt** [comment]
I think a blade view is good as it helps to integrate it easily with your custom proyect, leaving the developer handle permissions, routing, etc. I would go for minimal dependencies (framework) and then we should be able to extend the blade view to user our current javascript/css frameworks, or also contribute different views with different frameworks.

**Comment by romanzipp** [comment]
I've merged #21 and released [2.0.5](https://github.com/romanzipp/Laravel-Queue-Monitor/releases/tag/2.0.5). Some documentation can be found [in the README](https://github.com/romanzipp/Laravel-Queue-Monitor#ui).

I'll leave this issue open for further discussion 👍
