### ISSUE TITLE
Additional table or spot to track progress messages/debug info

### ISSUE THREAD

**Issue by owenconti** [romanzipp/Laravel-Queue-Monitor#23]
Hi @romanzipp,

I had a very similar idea to this package but luckily I searched first and found yours! It's a lot more advanced than what I was thinking.

The original reason I had thought of this idea was to be able to store debug info in a database table instead of in log files. With your package, this is possible via the `data` column. However, I also want to store data about the job somewhere too (model ID, etc). It feels messy to mix data about the job with the debug/log messages in the same column.

Would you consider either adding another column or possibly a second table to track messages? A second table could be useful because you could track extra data along with the message such as a timestamp, severity, etc.

I'd be happy to submit a PR for this if you're up for the feature!

**Comment by romanzipp** [comment]
Currently, I'm also using the `data` field for model relations by storing IDs & types in a `_references` field.

I don't think a second table is needed for the whole package and all users. Nonetheless you are free to [replace the existing `Monitor` model](https://github.com/romanzipp/Laravel-Queue-Monitor/blob/master/config/queue-monitor.php#L15) and add some custom relations.
