### ISSUE TITLE
Can not use queueMonitor() in routes

### ISSUE THREAD

**Issue by Kawetsch** [romanzipp/Laravel-Queue-Monitor#25]
Hey @romanzipp 

i just tried using your commit on my laravel instance. 
When I want to use the new route using `Route::queueMonitor();` in the `Route::prefix('jobs')->group` function I'm getting the following exception:
`UnexpectedValueException` - `Invalid route action: [App\\Http\\Controllers\\romanzipp\\QueueMonitor\\Controllers\\ShowQueueMonitorController].`.

I'm not sure what went wrong or how u registered `queueMonitor()` to be a method of Route().

Many thanks.

**Comment by romanzipp** [comment]
It looks like you Laravel application is prefixing the Queue-Monitor package controllers with your namespace defined in the `RouteServiceProvider`. Your propably looks like this:

```php
protected function mapWebRoutes()
{
    Route::middleware('web')
        ->namespace($this->namespace . '\App')
        ->group(base_path('routes/app.php'));
}
```

I'll take a look at how the official laravel scaffolding is managing this problem.

**Comment by Kawetsch** [comment]
Yes, the `RouteServiceProvider` contains `mapWebRoutes()`.

> I'll take a look at how the official laravel scaffolding is managing this problem.

That's awesome, thank you!

**Comment by Kawetsch** [comment]
Hey @romanzipp,

just solved by using different route file :)

**Comment by Kawetsch** [comment]
and changed the namespace in `RouteServiceProvider` to be an empty string.

**Comment by romanzipp** [comment]
Could you test out your previous Laravel route setup with the new [2.0.10](https://github.com/romanzipp/Laravel-Queue-Monitor/releases/tag/2.0.10) Version? I believe a namespace in the `RouteServiceProvider` should not longer interfere with the package controller.
