### ISSUE TITLE
New Job is not creating when using isMonitored

### ISSUE THREAD

**Issue by KasparWe** [romanzipp/Laravel-Queue-Monitor#26]
Hey,

just got following issue:

when dispatching a new job with `ExampleJob::dispatch()` while using 
`    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels, IsMonitored;` in the job class, the job is not getting created in the database. There is no error in the log.

When removing `IsMonitored` from `use` inside job class it's working.

Any ideas?

Thank you!

**Comment by pamekar** [comment]
Same problem here. Exact scenario.

**Comment by romanzipp** [comment]
Could you set up a bare-bone Laravel application for reproduction purposes?

**Comment by romanzipp** [comment]
Is the job created when using `ExampleJob::dispatchNow()` or dispatching the job via the `dispatch(new ExampleJob)` helper?

**Comment by romanzipp** [comment]
Are you implementing the `Illuminate\Contracts\Queue\ShouldQueue` interface? I was able to reproduce this issue when the dispatched job does not implement the queue contract.
