### ISSUE TITLE
queue monitor doesn't work with ShouldBroadcast

### ISSUE THREAD

**Issue by hanc2006** [romanzipp/Laravel-Queue-Monitor#27]
I was unable to monitor a job when implementing the **ShouldBroadcast** class. I use the database driver to queue the jobs, and `artisan queue:work ` to process the queue.

For the others job that implement the `ShouldQueue` class works fine!

**Comment by romanzipp** [comment]
Could you share some of your code? I'm unable to reproduce this issue.

**Comment by romanzipp** [comment]
Are you implementing the `ShouldBroadcast` interface **in addition** or **instead** of the `ShouldQueue` contract? It looks like Laravel does not dispatch any events for jobs that don't implement the `ShouldQueue` interface.

**Comment by hanc2006** [comment]
Sorry was my mistake. It works like expected.
