### ISSUE TITLE
Last attempt on failed job

### ISSUE THREAD

**Issue by niksib** [romanzipp/Laravel-Queue-Monitor#42]
Hello
When the job is failed and on the last attempt it stops in "Running" status but it already failed and don't change the status.
How can is fix it?
<img width="1637" alt="Screenshot 2020-12-17 at 15 59 33" src="https://user-images.githubusercontent.com/13890155/102497064-dcd6fa80-4080-11eb-86ac-1e67c081434a.png">

**Comment by romanzipp** [comment]
The package is listening to the [internal queue events](https://github.com/romanzipp/Laravel-Queue-Monitor/blob/master/src/Providers/QueueMonitorProvider.php#L51) and it looks like Laravel is dispatching a `JobFailed` event if the job fails on the last attempt.

I'll have a look into that!

**Comment by niksib** [comment]
I tried a few times and found:
If the queue_monitor table has 0 records it's work correctly
<img width="1677" alt="Screenshot 2020-12-17 at 16 46 27" src="https://user-images.githubusercontent.com/13890155/102502539-6a1d4d80-4087-11eb-9d55-a6abcdf4ab79.png">
But on the next try, the second attempt still have "Running" status, sometimes 2 and 3 attempts still in "Running" status
<img width="1667" alt="Screenshot 2020-12-17 at 16 48 31" src="https://user-images.githubusercontent.com/13890155/102502786-b4063380-4087-11eb-961a-48b4ac7c1e69.png">

**Comment by niksib** [comment]
I found some jobs when failed have the same started_at time
```
$monitor = $model::query()
->where('job_id', self::getJobId($job))
->orderBy('started_at', 'desc')
->first();
```
I think maybe change this on something like this - 
```
->where('job_id', self::getJobId($job))
->where('attempt', $attempt)
```
<img width="152" alt="Screenshot 2020-12-17 at 16 57 51" src="https://user-images.githubusercontent.com/13890155/102504023-02680200-4089-11eb-9e93-94c5db06f042.png">

**Comment by romanzipp** [comment]
Unforntunately I didn't manage to set up a unit test for that case. Nontheless could you test the new `fix-max-attempt-failing` branch in your application?

Just change the composer version to

```
"romanzipp/laravel-queue-monitor": "dev-fix-max-attempt-failing"
```

and run `composer install` / `composer update`

I've added a decending order query to the monitor model retrieval

```diff
+ ->orderByDesc('attempt')
```

**Comment by niksib** [comment]
It works, thanks.
