### ISSUE TITLE
Error with mb_strcut on jobFinished with exception

### ISSUE THREAD

**Issue by leanec** [romanzipp/Laravel-Queue-Monitor#44]
Hello,

This error happens in PHP 32 bits
MAX_BYTES_LONGTEXT = 4294967295 is taken as float because it exceeds the maximum for an integer

![image](https://user-images.githubusercontent.com/1708772/102559383-7d8fdf00-40ae-11eb-89e6-071dd6a8b93e.png)

**Comment by romanzipp** [comment]
I've opened a PR #46 for this problem. Don't think I will go this way but it will work for you until then

**Comment by leanec** [comment]
With that change it works fine

**Comment by dbg1995** [comment]
@romanzipp This error still occurs on the php version <= 7.2.x. 
Please help me check 
http://sandbox.onlinephpfunctions.com/code/ba094d2d27a063560883793cfadf703fbbdb3c01
