### ISSUE TITLE
Having issue with Job Retry

### ISSUE THREAD

**Issue by aqibj12** [romanzipp/Laravel-Queue-Monitor#45]
Hi I am using this package with my laravel 6. But having issue on Job retry I specified public $tries = 0;  in my job but yet my job is retrying again and again. Can you please help me at this.

**Comment by romanzipp** [comment]
It looks like this isn't really a package issue but rather misconfiguration. I believe `$tries = 0` tells Laravel to always restart the job. Try setting the value to `1` as the [documentation states](https://laravel.com/docs/6.x/queues#max-job-attempts-and-timeout)
