### ISSUE TITLE
Error with mb_strcut on jobFinished with exception on the php version <= 7.2.x.

### ISSUE THREAD

**Issue by dbg1995** [romanzipp/Laravel-Queue-Monitor#50]
After [this error](https://github.com/romanzipp/Laravel-Queue-Monitor/pull/46) has been fixed, but this error still occurs on the php version <= 7.2.x.
Please help me check
http://sandbox.onlinephpfunctions.com/code/ba094d2d27a063560883793cfadf703fbbdb3c01

**Run on PHP version: 7.2.31**

```
<?php
var_dump(PHP_INT_MAX);
var_dump( mb_strcut("ss", 0, min(PHP_INT_MAX,4294967295)));
```

**Output:** 
```
int(9223372036854775807)
bool(false)
```

**Comment by romanzipp** [comment]
Unfortunately I don't have any idea how to fixes this issue at the time. Removing the character limit eventually causes database exceptions
