### ISSUE TITLE
[Feature] Update DURATION on Running task

### ISSUE THREAD

**Issue by javis** [romanzipp/Laravel-Queue-Monitor#51]
Being able to elapsed time of unfinished jobs is particuylarly useful for long running task, please update the "Duration" column on each progress update

![image](https://user-images.githubusercontent.com/951888/107421955-63480f80-6af9-11eb-848f-1fcc26dfa69f.png)

**Comment by romanzipp** [comment]
The property used within the view actually didn't exist.

I've added two new methods and updated the view 👍

```php
public function getRemainingSeconds(Carbon $now = null): float
public function getRemainingInterval(Carbon $now = null): CarbonInterval
```

**Comment by javis** [comment]
Great! Thanks!
