### ISSUE TITLE
Action App\Http\Controllers\romanzipp\QueueMonitor\Controllers\PurgeMonitorsController not defined

### ISSUE THREAD

**Issue by javis** [romanzipp/Laravel-Queue-Monitor#54]
Error: 

```
InvalidArgumentException
Action App\Http\Controllers\romanzipp\QueueMonitor\Controllers\PurgeMonitorsController not defined. (View: /home/vagrant/ngcloud/vendor/romanzipp/laravel-queue-monitor/views/jobs.blade.php)

```
when enabling purge in config file. Same happens with allow deletion. the `action()` function is unable to fiind the action for the controller class because the strings needs to start with `\`

**Comment by huzaifaarain** [comment]
Having the same issue, the problem is with laravel `action()` helper function.

Laravel 8.x support absolute controller with namespace while the versions <= 8.x takes a relative controller path with respect to `App\Http\Controllers`, i was wondering why @romanzipp is not using `Named Routes`.
