### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by f1mp3r** [romanzipp/Laravel-Queue-Monitor#60]
Hi, I was curious if lumen support was considered at some point as currently it gives this error when trying to run the migration:
`Call to undefined method Laravel\Lumen\Application::configurationIsCached();`

**Comment by romanzipp** [comment]
I haven't worked with Lumen yet. Feel free to send a PR regarding this

**Comment by Rasoul-Karimi** [comment]
now support lumen 9 or not??

**Comment by romanzipp** [comment]
As I've said before, feel free to create a PR for Lumen support
