### ISSUE TITLE
Any thoughts on how this might be used to kill a running job?

### ISSUE THREAD

**Issue by oobi** [romanzipp/Laravel-Queue-Monitor#70]
This is probably a feature request but I haven't found any good info on this in the Laravel docs.

Is there a way to hook the "delete" action on a running job to kill the task itself or interrupt it?

**Comment by romanzipp** [comment]
Laravel does not include include any functionality like this out of the box. I've already implemented a similar functionality by storing the process ID in the queue data.

```php
public function handle(): void
{
    if (function_exists('posix_getpid')) {
        $this->queueData(['process_id' => posix_getpid()]);
    }
}
```

You could you [`posix_kill`](https://www.php.net/manual/de/function.posix-kill.php) to kill the process.

I'll look into this further and setup a PR 👍
