### ISSUE TITLE
Argument 3 passed to QueueMonitor::jobFinished() must implement interface Throwable or be null, string given

### ISSUE THREAD

**Issue by idealerror** [romanzipp/Laravel-Queue-Monitor#71]
Hello,

When a job fails, it's failing with this error:

```
Argument 3 passed to romanzipp\QueueMonitor\Services\QueueMonitor::jobFinished() must implement interface Throwable or be null, string given, called in /var/www/html/vendor/romanzipp/laravel-queue-monitor/src/Services/QueueMonitor.php on line 70
```

Any ideas why this is happening? Possibly due to this an exception where I'm failing the job myself?

```php
try {
            $output = DB::connection()->select($query);
        } catch(\Illuminate\Database\QueryException $ex){
            $this->fail($ex->getMessage());
        }
```

**Comment by romanzipp** [comment]
[The Laravel fail method](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Queue/InteractsWithQueue.php#L41) expects an exception (instance of `Throwable`) as first argument. You are only providing a string.
