### ISSUE TITLE
Laravel Excel compatibility

### ISSUE THREAD

**Issue by jeroen-hso** [romanzipp/Laravel-Queue-Monitor#98]
Hi, I would like to use your package to monitor Excel imports. Are there known issues between Laravel Excel and this package? I have implemented ShouldQueue and IsMonitored, but jobs are not visible in your monitor (success and failed jobs)

https://docs.laravel-excel.com/3.1/imports/queued.html

Thanks in advance for your help.

**Comment by romanzipp** [comment]
Could you try adding the following method to the job:

```php
public function failed(Throwable $e) 
{
    parent::failed($e);
    throw $e;
}
```

**Comment by jeroen-hso** [comment]
Hi Roman,

Thanks for your help. When I add this method I get two intelephense errors and import aborts with the following error message:

Cannot use "parent" when current class scope has no parent
