### ISSUE TITLE
Running `dispatch()` fails to load Closure

### ISSUE THREAD

**Issue by zero-to-prod** [romanzipp/Laravel-Queue-Monitor#99]
testing.ERROR: class_parents(): Class Closure (...) does not exist and could not be loaded {"exception":"[object] (ErrorException(code: 0): class_parents(): Class Closure (...) does not exist and could not be loaded at /var/www/backend/vendor/romanzipp/laravel-queue-monitor/src/Services/ClassUses.php:49)

**Comment by zero-to-prod** [comment]
I can confirm this is an issue on a new project.

**Comment by romanzipp** [comment]
It would be helpful if you could provide any more information than just a stacktrace. Such as code snippets, reproduction steps, installed dependencies etc.
